name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
     
      - name: Pull Postgres docker
        run: docker pull postgres
      
      - name: Run Postgres Container
        run: docker run --name postgrestp4 -e POSTGRES_USER=tp_devops -e POSTGRES_PASSWORD=tp_devops -e POSTGRES_DB=tp_devops --cpus=1 --expose=5432 --memory=50M -d postgres

      - name: Run gradles test
        run: ./gradlew check -debug

      - name: Build jar
        run: ./gradlew assemble

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_NAME }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-docker-hub-namespace/my-docker-hub-repository
          tag_with_ref: true
